version: '3.3'
services:
    apache:
        build: .
        hostname: OPTIONAL
        container_name: OPTIONAL
        volumes:
            - ./apache/apache2.conf:/etc/apache2/apache2.conf:ro
            - ./apache/site1.conf:/etc/apache2/sites-available/site1.conf:ro
            - ./certbot/www:/var/www/certbot/:ro
        ports:
            - '80:80'
            - '443:443'
    certbot:
        image: certbot/certbot:latest
        volumes:
            - ./certbot/www/:/var/www/certbot/:rw