[http.routers]
  [http.routers.force-https]
    entryPoints = ["http"]
    rule = "HostRegexp(`{any:.+}`)"
    middlewares = ["force-https"]
    priority = 1
    service = "noop"

[http.middlewares]
  [http.middlewares.force-https.redirectScheme]
    scheme = "https"

[http.services]
  [http.services.noop.loadBalancer]
    [[http.services.noop.loadBalancer.servers]]
      url = "http://${{EXTERNAL_DOMAIN}}"
